# Login
POST http://13.60.32.234:8000/login
Content-Type: application/json


{
  "username": "TestUser2",
  "password": "ShowTime20"
}

###

# Enter the token after login/signup for generate the other sections
# For example:
@token = e02b045be0217d6f78ada2f2c5c05119716ee629

###

# Signup
POST http://13.60.32.234:8000/signup
Content-Type: application/json


{"username": "TestUser4", "password": "ShowTime40", "email": "test4@mail.com"}
 
###

# Token Check
GET http://13.60.32.234:8000/test-token
Content-Type: application/json
Authorization: Token {{token}}

{}
 
###
# All-Users Check (Returns usernames and email)
GET http://13.60.32.234:8000/users-list
Content-Type: application/json

{}

###

# All Messages for valid user
GET  http://13.60.32.234:8000/messages_center/all_messages
Content-Type: application/json
Authorization: Token {{token}}

{}

###

# Unread Messages for valid user
GET  http://13.60.32.234:8000/messages_center/unread_messages
Content-Type: application/json
Authorization: Token {{token}}

{}

###

# Message details For valid user - will change the message status 
GET http://13.60.32.234:8000/messages_center/message_details/2/
Content-Type: application/json
Authorization: Token {{token}}

{}

###

# Delete message - Allows only with permissions 
DELETE  http://13.60.32.234:8000/messages_center/message_delete/1/
Content-Type: application/json
Authorization: Token {{token}}

{}

###

# Create message - the receiver name should be a real user!
POST http://13.60.32.234:8000/messages_center/create_message/
Content-Type: application/json
Authorization: Token {{token}}

{
    "receiver": "admin",
    "subject": "answer",
    "content": "Im pretty good!"
}
